-- Sample Products for Priya Herbal
INSERT INTO public.products (name, slug, description, long_description, price, original_price, category, image_url, images, rating, review_count, in_stock, quantity_available) VALUES
('Premium Neem Hair Oil', 'neem-hair-oil', 'Pure neem oil for healthy hair growth', 'Enriched with pure neem extract and coconut oil to prevent hair fall and promote growth. Perfect for all hair types.', 249, 399, 'Hair Care', '/placeholder.svg?height=400&width=400', '[]', 4.7, 234, true, 150),
('Turmeric Face Pack', 'turmeric-face-pack', 'Natural turmeric and gram flour face pack', 'Brighten your complexion naturally with our turmeric and gram flour blend. Reduces acne and improves skin radiance.', 199, 299, 'Skin Care', '/placeholder.svg?height=400&width=400', 'A', 4.6, 189, true, 200),
('Ashwagandha Powder', 'ashwagandha-powder', 'Pure organic ashwagandha powder', 'Boost immunity and reduce stress with our premium ashwagandha powder. Perfect for daily wellness routine.', 399, 599, 'Immunity', '/placeholder.svg?height=400&width=400', '[]', 4.8, 312, true, 100),
('Tulsi Green Tea', 'tulsi-green-tea', 'Organic tulsi and green tea blend', 'Antioxidant-rich tulsi green tea for daily wellness and immune support. 25 tea bags per pack.', 179, 259, 'Immunity', '/placeholder.svg?height=400&width=400', '[]', 4.5, 156, true, 250),
('Brahmi Hair Oil', 'brahmi-hair-oil', 'Brahmi infused cooling hair oil', 'Cool and nourish your scalp with brahmi oil. Reduces hair fall and promotes natural growth.', 229, 349, 'Hair Care', '/placeholder.svg?height=400&width=400', '[]', 4.7, 198, true, 120),
('Hibiscus Face Mask', 'hibiscus-face-mask', 'Hibiscus and rose clay mask', 'Deep cleansing mask with hibiscus and natural clay. Removes impurities and tightens pores.', 249, 399, 'Skin Care', '/placeholder.svg?height=400&width=400', '[]', 4.4, 142, true, 180),
('Triphala Powder', 'triphala-powder', 'Three-fruit Ayurvedic blend', 'Traditional triphala formula for digestive health and detoxification. Pure organic ingredients.', 349, 499, 'Wellness', '/placeholder.svg?height=400&width=400', '[]', 4.9, 276, true, 90),
('Aloe Vera Gel', 'aloe-vera-gel', '100% pure aloe vera gel', 'Soothing and hydrating aloe vera gel for skin and hair care. Organic and preservative-free.', 199, 299, 'Skin Care', '/placeholder.svg?height=400&width=400', '[]', 4.6, 201, true, 220),
('Bhringraj Oil', 'bhringraj-oil', 'Bhringraj herbal hair oil', 'The king of herbs for hair. Prevents premature graying and strengthens hair roots.', 269, 429, 'Hair Care', '/placeholder.svg?height=400&width=400', '[]', 4.8, 267, true, 110),
('Sandalwood Face Cream', 'sandalwood-face-cream', 'Premium sandalwood moisturizing cream', 'Luxurious sandalwood cream for soft, glowing skin. Perfect for all seasons and skin types.', 499, 799, 'Skin Care', '/placeholder.svg?height=400&width=400', '[]', 4.7, 189, true, 80),
('Moringa Protein Powder', 'moringa-protein-powder', 'Organic moringa leaf protein powder', 'High-protein moringa powder for energy and vitality. Complete amino acid profile.', 599, 899, 'Wellness', '/placeholder.svg?height=400&width=400', '[]', 4.5, 134, true, 60);
